export const PROCESSING_STEPS = [
  "Sharpening Crayons",
  "Googling 'What's Drip?'",
  "It's Buffering...",
  "Do We Have an 'Enhance' Button?",
  "Asking Jeevus for Fashion Advice",
  "Is Black & White Colorful?",
  "Consulting Clippy",
  "Do People Still Say No Cap?",
  "Just Fold It In",
  "Is 'No Cap' About Hats?",
  "Updating AIM Away Message",
  "Saving to Floppy Disk",
  "Can Adults Legally Use 'Rizz?'",
  "YouTube Sewing Tutorials",
  "Letting AI Cook",
  "Waiting For AOL to Connect",
  "Replacing Printer Cartridge",
  "Mom! I'm On The Phone!",
  "Be Kind, Rewind",
  "Checking Limewire",
  "Feeding Our Tamagotchi",
  "Dialing Up",
  "Putting Images On the Line",
  "Scanning for Drip… Please Insert Disc 2",
  "Syncing With Palm Pilot",
  "Saving to Floppy… Do Not Remove Disk",
  "Is It Floppy Disc, or Disk?"
];
