export const PROCESSING_STEPS = [
  "Sharpening Crayons",
  "Googling 'What's Drip?'",
  "It's Buffering...",
  "Do We Have an 'Enhance' Button?",
  "Asking Jeevus for Fashion Advice",
  "Is Black & White Colorful?",
  "Consulting Clippy",
  "Do People Still Say No Cap?",
  "Just Fold It In",
  "Is 'No Cap' About Hats?",
  "Updating AIM Away Message",
  "Saving to Floppy Disk",
  "Can Adults Legally Use 'Rizz?'",
  "Youtube Sewing Tutorials",
  "Letting AI Cook",
  "Waiting For AOL to Connect",
  "Replacing Printer Cartridge",
];
